---
id: Filesystem
name: Filesystem
full: Standalone object-oriented Filesystem library
description: Traverse and manipulate unixoid filesystems in library without dependences or framework specific assumptions.
list: dev
type: library
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 1.0.0alpha2
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^8.1
builds:
 - 8.1
 - 7.4